name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository 🛒
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Node ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: "18.16.0"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies 🔧
        # include devDependencies https://stackoverflow.com/a/64648870
        run: npm ci --audit=false --include=dev --include=optional --include=peer

      - name: Build package 🏗️
        run: npm run build
